# Generated by Django 5.2.4 on 2025-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(help_text='Seleccione una o varias categorías para este producto', related_name='products', to='categories.category', verbose_name='Categorías'),
        ),
    ]
