# Generated by Django 5.2.4 on 2025-07-17 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Descuento'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario'),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Porcentaje de ganancia sobre el costo con IVA', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% de Ganancia'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=19.0, help_text='Porcentaje de impuesto aplicable', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% de IVA'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo base del producto sin impuestos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo neto'),
            preserve_default=False,
        ),
    ]
