# Generated by Django 5.2.4 on 2025-07-17 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_inventorymovement_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo base del producto sin impuestos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo neto'),
        ),
    ]
