# Generated by Django 5.2.4 on 2025-07-21 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='_stock',
            field=models.IntegerField(db_column='stock', default=0, help_text='Solo se usa si el producto no tiene variantes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock manual'),
        ),
    ]
