# Generated by Django 5.2.4 on 2025-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_stock_product__stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variants',
            field=models.BooleanField(default=True, help_text='Marcar si este producto se venderá con variantes (tallas, colores, etc).', verbose_name='¿Tiene Variantes?'),
        ),
    ]
