# Generated by Django 5.2.4 on 2025-08-13 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_absolutecategory'),
        ('products', '0010_product_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='absolute_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.absolutecategory'),
        ),
    ]
