# Generated by Django 5.2.4 on 2025-09-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_absolute_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='adjust_reason',
            field=models.TextField(blank=True, help_text="Obligatorio cuando movement_type = 'adjust'", verbose_name='Motivo del ajuste'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
