# Generated by Django 5.2.4 on 2025-09-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_inventorymovement_adjust_reason_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='adjust_reason',
            field=models.TextField(blank=True, help_text='Explica por qué se realiza el ajuste (obligatorio para auditoría).', verbose_name='Motivo del ajuste'),
        ),
    ]
