# Generated by Django 5.2.4 on 2025-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_inventorymovement_adjust_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='reservation_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID de Reservation si proviene de una reserva', null=True),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='adjust_reason',
            field=models.TextField(blank=True, help_text='Obligatorio solo para ajustes.', verbose_name='Motivo del ajuste'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjust', 'Ajuste'), ('reserve', 'Reserva')], max_length=10),
        ),
    ]
