# Generated by Django 5.2.4 on 2025-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_inventorymovement_reservation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='consumed',
            field=models.BooleanField(default=False, help_text='Marca si un movimiento de reserva ya fue consumido en una venta'),
        ),
    ]
