# Generated by Django 5.2.4 on 2025-09-04 14:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_alter_inventorymovement_adjust_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente')),
                ('client_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de factura')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('paid', models.BooleanField(default=False, verbose_name='Pagada')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('inventory_moved', models.BooleanField(default=False, verbose_name='Movimientos aplicados')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente')),
                ('client_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del cliente')),
                ('client_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono del cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto abonado')),
                ('due_date', models.DateTimeField(verbose_name='Fecha límite')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='active', max_length=20, verbose_name='Estado')),
                ('movement_created', models.BooleanField(default=False, verbose_name='Movimientos generados')),
            ],
            options={
                'verbose_name': 'Apartado',
                'verbose_name_plural': 'Apartados',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Producto facturado',
                'verbose_name_plural': 'Productos facturados',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.reservation', verbose_name='Apartado relacionado'),
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.reservation')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Producto apartado',
                'verbose_name_plural': 'Productos apartados',
            },
        ),
    ]
