# Generated by Django 5.2.4 on 2025-09-08 22:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto pagado'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('EF', 'Efectivo'), ('DI', 'Digital')], max_length=2, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('NEQUI', 'Nequi'), ('DAVIPLATA', 'Daviplata')], max_length=20, null=True, verbose_name='Proveedor digital'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado factura'),
        ),
    ]
