# Generated by Django 5.2.4 on 2025-09-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del cliente'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono del cliente'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del cliente'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono del cliente'),
        ),
    ]
