# Generated by Django 5.2.4 on 2025-08-27 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_auditlog_action_alter_auditlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('other', 'Otro')], max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
