# Generated by Django 5.2.4 on 2025-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clean_auditlog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
