# Generated by Django 5.2.4 on 2026-01-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automático')], max_length=10)),
                ('file', models.FileField(upload_to='database_backups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Respaldo de Base de Datos',
                'verbose_name_plural': 'Respaldos de Base de Datos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Estado de BD',
                'verbose_name_plural': 'Registros de Estado de BD',
                'ordering': ['-created_at'],
            },
        ),
    ]
