# Generated by Django 5.2.4 on 2026-01-16 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_label', models.CharField(blank=True, max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('format', models.CharField(default='xlsx', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_reports/')),
                ('preview', models.JSONField(blank=True, null=True)),
                ('rows_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('daily', 'Reporte Diario'), ('monthly', 'Reporte Mensual'), ('inventory', 'Reporte Inventario'), ('products', 'Reporte Productos'), ('categories', 'Reporte Categorías'), ('sales', 'Reporte Ventas'), ('reservations', 'Reporte Reservas'), ('audit', 'Reporte Auditoría'), ('top_products', 'Reporte Top Productos'), ('custom', 'Reporte Personalizado')], default='custom', max_length=40)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('export_formats', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Definición de Reporte',
                'verbose_name_plural': 'Definiciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/')),
                ('builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reporte',
                'ordering': ['name'],
            },
        ),
    ]
