# Generated by Django 5.2.4 on 2025-09-12 01:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Plantilla de Reporte', 'verbose_name_plural': 'Plantillas de Reporte'},
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='format',
            field=models.CharField(default='xlsx', max_length=10),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='preview',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='report_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='rows_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='builtin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generatedreport',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates/'),
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('daily', 'Reporte Diario'), ('monthly', 'Reporte Mensual'), ('inventory', 'Reporte Inventario'), ('products', 'Reporte Productos'), ('categories', 'Reporte Categorías'), ('sales', 'Reporte Ventas'), ('reservations', 'Reporte Reservas'), ('audit', 'Reporte Auditoría'), ('top_products', 'Reporte Top Productos'), ('custom', 'Reporte Personalizado')], default='custom', max_length=40)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('export_formats', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_definitions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Definición de Reporte',
                'verbose_name_plural': 'Definiciones de Reportes',
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.reportdefinition'),
        ),
    ]
