# Generated by Django 5.2.4 on 2025-08-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0011_product_absolute_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformativeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Descripción')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='carousel_info/', verbose_name='Imagen 1 (opcional)')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='carousel_info/', verbose_name='Imagen 2 (opcional)')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='carousel_info/', verbose_name='Imagen 3 (opcional)')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link (interno o externo)')),
                ('bg_color', models.CharField(default='#198754', help_text='HEX (#RRGGBB)', max_length=7, verbose_name='Color de fondo')),
                ('layout', models.CharField(choices=[('default', 'Texto izquierda + imagen derecha'), ('full_text', 'Texto centrado sin imagen'), ('icon_text', 'Ícono grande + texto abajo'), ('three_img', 'Texto + hasta 3 imágenes'), ('image_bg', 'Imagen de fondo con overlay de texto'), ('split_banner', 'Banner dividido en dos columnas'), ('minimal', 'Diseño minimalista (solo título y botón)')], default='default', max_length=20, verbose_name='Diseño de tarjeta')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es slide predeterminada')),
                ('default_type', models.CharField(blank=True, choices=[('welcome', 'Bienvenida'), ('about', 'Nosotros y Contacto')], help_text='Usado para identificar slides fijos como Bienvenida o Nosotros', max_length=20, null=True, verbose_name='Tipo de slide predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Tarjeta informativa',
                'verbose_name_plural': 'Carrusel: Tarjetas informativas',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, help_text='Si se deja vacío, se usará el nombre del producto', max_length=100, verbose_name='Título personalizado (opcional)')),
                ('custom_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo personalizado (opcional)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Determina la posición en el carrusel (menor número = primero)', verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar para mostrar este producto en el carrusel', verbose_name='Activo')),
                ('bg_color', models.CharField(default='#0d6efd', help_text='HEX (#RRGGBB)', max_length=7, verbose_name='Color de fondo')),
                ('layout', models.CharField(choices=[('default', 'Texto izquierda + imagen derecha'), ('full_text', 'Texto centrado sin imagen'), ('icon_text', 'Ícono grande + texto abajo'), ('two_img', 'Texto + hasta 2 imágenes'), ('three_img', 'Texto + hasta 3 imágenes'), ('split_banner', 'Banner dividido en dos columnas'), ('minimal', 'Diseño minimalista (solo título y botón)')], default='default', max_length=20, verbose_name='Diseño de tarjeta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('product', models.OneToOneField(help_text='Seleccione un producto existente para mostrar en el carrusel', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto destacado')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Carrusel de Productos Destacados',
                'ordering': ['display_order', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('product',), name='unique_featured_product')],
            },
        ),
    ]
