# Generated by Django 5.2.4 on 2025-08-20 19:06

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE frontend_informativecarousel
                ADD COLUMN IF NOT EXISTS is_default boolean NOT NULL DEFAULT FALSE;
            """,
            reverse_sql="""
                ALTER TABLE frontend_informativecarousel
                DROP COLUMN IF EXISTS is_default;
            """,
        ),
    ]
