# Generated by Django 5.2.4 on 2026-01-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproductcarousel',
            name='product',
            field=models.OneToOneField(help_text='Seleccione un producto existente para mostrar en el carrusel', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto destacado'),
        ),
        migrations.AddConstraint(
            model_name='featuredproductcarousel',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_featured_product'),
        ),
    ]
