# Generated by Django 5.2.4 on 2026-01-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informativecarousel',
            name='image1_optimized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='informativecarousel',
            name='image2_optimized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='informativecarousel',
            name='image3_optimized',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='featuredproductcarousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='bg_color',
            field=models.CharField(default='#198754', max_length=7),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='default_type',
            field=models.CharField(blank=True, choices=[('welcome', 'Bienvenida'), ('about', 'Nosotros')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_info/'),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_info/'),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_info/'),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='layout',
            field=models.CharField(choices=[('default', 'Texto izquierda + imagen derecha'), ('full_text', 'Texto centrado sin imagen'), ('icon_text', 'Ícono grande + texto abajo'), ('three_img', 'Texto + hasta 3 imágenes'), ('image_bg', 'Imagen de fondo con overlay'), ('split_banner', 'Banner dividido'), ('minimal', 'Minimal')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='informativecarousel',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
