# Generated by Django 5.2.4 on 2025-08-20 19:07

from django.db import migrations

def create_default_slides(apps, schema_editor):
    InformativeCarousel = apps.get_model("frontend", "InformativeCarousel")

    # Bienvenida
    InformativeCarousel.objects.get_or_create(
        default_type="welcome",
        defaults={
            "title": "¡Bienvenidos a MeloSport!",
            "description": "Encuentra lo mejor en ropa y artículos deportivos.",
            "layout": "default",           # Texto izq + imagen der (o como lo renderices)
            "bg_color": "#198754",
            "is_active": True,
            "is_default": True,
            "display_order": 0,
            # "link": ""  # opcional
        },
    )

    # Nosotros + Contacto (dos columnas)
    InformativeCarousel.objects.get_or_create(
        default_type="about",
        defaults={
            "title": "Nosotros",
            "description": "Conócenos y contáctanos.",
            "layout": "split_banner",      # dos columnas
            "bg_color": "#0d6efd",
            "is_active": True,
            "is_default": True,
            "display_order": 1,
            "link": "/nosotros",           # que el botón te lleve a la página de Nosotros
        },
    )

def undo_default_slides(apps, schema_editor):
    InformativeCarousel = apps.get_model("frontend", "InformativeCarousel")
    InformativeCarousel.objects.filter(default_type__in=["welcome", "about"]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_add_is_default_column"),
    ]

    operations = [
        migrations.RunPython(create_default_slides, undo_default_slides),
    ]
